apiVersion: v1
kind: PersistentVolume
metadata:
  name: book-shop-files-pv
spec:
  capacity:
    storage: "{{ .Values.volume.capacity }}"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "{{ .Values.volume.fileUploadedPath }}"
  storageClassName: manual
