apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: book-shop-files-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "{{ .Values.volume.capacity }}"
  storageClassName: manual
