---
# Source: book-shop-frontend/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
data:
  config.json: |
    {
       "API_URL": "http://localhost:8000"
    }
---
# Source: book-shop-frontend/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-release-book-shop-frontend
  labels:
    helm.sh/chart: book-shop-frontend-0.1.0
    app.kubernetes.io/name: book-shop-frontend
    app.kubernetes.io/instance: my-release
    app.kubernetes.io/version: "1.16.0"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: book-shop-frontend
    app.kubernetes.io/instance: my-release
---
# Source: book-shop-frontend/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-release-book-shop-frontend
  labels:
    app: book-shop-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-shop-frontend
  template:
    metadata:
      labels:
        app: book-shop-frontend
    spec:
      containers:
        - name: bookshopfrontend
          image: "sieunhantanbao/book-shop-frontend:v3"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/nginx/html/config.json
              subPath: config.json
      volumes:
        - name: config-volume
          configMap:
            name: frontend-config
