# ./.github/workflows/ci-quality-check.yml

name: Continues Integration - Quality check
on:
  pull_request:
    branches:
      - main

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
          fetch-depth: 1 # Only get the latest commit; 0: get will git commit

    - name: Setup prerequisites
      uses: ./.github/actions/prerequisites

    - name: Rename environment file
      run: mv src/service/sample.env src/service/.env

    - name: Run backend tests
      run: |
        cd src/service
        pytest
  # TODO: test front-end